trigger:
  branches:
    include:
    - main
  paths:
    include:
    - bicep/modules
    - pipelines/iac-pipeline.yml

name: IaC Pipeline

variables:

- group: tony-gilmore-variables

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@2
  displayName: Deploy with Bicep
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(serviceConnectionName)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: './bicep/module2.bicep' 
    overrideParameters: '-prefix "$(prefix)" -sqlAdministratorLogin "$(sqlAdminUsername)" -sqlAdministratorLoginPassword "$(sqlAdminPassword)"'
    deploymentMode: 'Incremental'
    deploymentName: '$(prefix)'
